service: bastrap

image: brkn/bastrap

servers:
  web:
    - 23.88.49.186

proxy:
  ssl: true
  host: bastrap.com
  # Proxy connects to your container on port 80 by default.
  app_port: 4000

registry:
  server: ghcr.io
  username: brkn
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  remote: ssh://root@23.88.49.186

env:
  clear:
    PORT: 4000
  secret:
    - KAMAL_REGISTRY_PASSWORD
    - SECRET_KEY_BASE
    - DATABASE_URL
    - PHX_HOST

accessories:
  db:
    image: postgres:15
    host: 23.88.49.186
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: "bastrap"
        POSTGRES_DB: "bastrap_production"
      secret:
        - POSTGRES_PASSWORD
    files:
      - config/setup_production_db.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
